---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: bmZwbGZrMHoK
  CLOUDINARY_KEY: NTUxODQ1NTc2NTIzNTI2Cg==
  CLOUDINARY_SECRET: UWItczFld3l3N2dKMnJaNXB4UlYtU25BN0owCg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZWEoxYmpNME9USTJJaXdpWVNJNkltTnRjalJxYm1wellUQmlZVE15ZUhOcU9UazVaV2h5T1RFaWZRLnQ2QWFpalBqWkNVX3hsU3VkeXlFbmcK
  DB_URL: bW9uZ29kYitzcnY6Ly9hcnVudmVsYWswM19kYl91c2VyOk51cmFhazEyM0BhcnVuMzQ5MjYuOG1qbnBqMS5tb25nb2RiLm5ldC8/YXBwTmFtZT1hcnVuMzQ5MjYK
  SECRET: ZGV2b3BzcHJvamVjdAo=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: dockerarasan/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
